Imports:

In [ ]:
from engine.util import HiddenLayer, Softmax, Loss

Visual:

![mod1](mod1.png)

Model definition:

In [ ]:
model = [
    HiddenLayer(2, 2),
    Softmax(2, 1)
]

In [2]:
import numpy as np
weights = np.random.rand(2, 2)
print(weights)

[[0.83505794 0.14514   ]
 [0.9215563  0.88162724]]


In [ ]:
from engine.util import HiddenLayer, Softmax, Loss
s = Softmax(4, 1)

In [20]:
inputs = np.array([[3,3.5,4,4.5],[1,1.5,2,2.6]])
def activation_softmax():
    """Softmax activation function"""
    inext = np.exp(inputs).T
    print(inext)
    d = np.sum(inext, axis=0)
    print(d)
    return np.divide(inext, d).T
    #print(np.sum(inext, axis=0))

print(activation_softmax())

[[20.08553692  2.71828183]
 [33.11545196  4.48168907]
 [54.59815003  7.3890561 ]
 [90.0171313  13.46373804]]
[197.81627022  28.05276503]
[[0.10153632 0.1674051  0.27600434 0.45505423]
 [0.09689889 0.15975926 0.2633985  0.47994335]]
